name: 'Scrape usage data (nightly)'

on:
  workflow_dispatch:
  schedule:
    - cron: '05 0 * * *' # run daily at 5 minutes past midnight

jobs:
  main:
    defaults:
      run:
        working-directory: ./backend
    name: main
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.7
      - name: setup uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: install dependencies
        run: uv sync --all-extras --dev
      - name: install chromedriver
        uses: nanasess/setup-chromedriver@v2
      - name: scrape data and upload to vercel KV
        env:
          SWITCH2_USERNAME: ${{secrets.switch2_username}}
          SWITCH2_PASSWORD: ${{secrets.switch2_password}}
          KV_REST_API_TOKEN: ${{secrets.kv_rest_api_token}}
          KV_REST_API_URL: ${{secrets.kv_rest_api_url}}
        run: uv run scrape.py
